### PR TITLE
Compile in Ubuntu 22.04, 24.04 & C++17

### PR DESCRIPTION
**Pull request by lucasw**
Work-in-progress, there are a couple of warnings I didn't eliminate- one requires rviz changes (OgreVector3.h includes), another in eigen:

```
In file included from /usr/include/eigen3/Eigen/Core:337,
                 from /usr/include/eigen3/Eigen/Dense:1,
                 from /home/lucasw/catkin_ws/src/fuse/fuse_viz/include/fuse_viz/mapped_covariance_visual.h:41,
                 from /home/lucasw/catkin_ws/src/fuse/fuse_viz/src/mapped_covariance_visual.cpp:30:
/usr/include/eigen3/Eigen/src/Core/products/SelfadjointMatrixVector.h: In function ‘static void Eigen::internal::selfadjoint_product_impl<Lhs, LhsMode, false, Rhs, 0, true>::run(Dest&, const Lhs&, const Rhs&, const Scalar&) [with Dest = Eigen::Block<Eigen::Matrix<double, 1, 1, 0, 1, 1>, -1, 1, false>; Lhs = Eigen::Block<Eigen::Matrix<double, 2, 2>, -1, -1, false>; int LhsMode = 17; Rhs = Eigen::CwiseBinaryOp<Eigen::internal::scalar_product_op<double, double>, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, const Eigen::Matrix<double, -1, 1, 0, 2, 1> >, const Eigen::Block<Eigen::Block<Eigen::Matrix<double, 2, 2>, 2, 1, true>, -1, 1, false> >]’:
/usr/include/eigen3/Eigen/src/Core/products/SelfadjointMatrixVector.h:229:7: error: ‘result’ may be used uninitialized [-Werror=maybe-uninitialized]
  227 |     internal::selfadjoint_matrix_vector_product<Scalar, Index, (internal::traits<ActualLhsTypeCleaned>::Flags&RowMajorBit) ? RowMajor : ColMajor,
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  228 |                                                 int(LhsUpLo), bool(LhsBlasTraits::NeedToConjugate), bool(RhsBlasTraits::NeedToConjugate)>::run
      |                                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  229 |       (
      |       ^
  230 |         lhs.rows(),                             // size
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  231 |         &lhs.coeffRef(0,0),  lhs.outerStride(), // lhs info
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  232 |         actualRhsPtr,                           // rhs info
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  233 |         actualDestPtr,                          // result info
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  234 |         actualAlpha                             // scale factor
      |         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  235 |       );
      |       ~
/usr/include/eigen3/Eigen/src/Core/products/SelfadjointMatrixVector.h:41:6: note: by argument 3 of type ‘const double*’ to ‘static void Eigen::internal::selfadjoint_matrix_vector_product<Scalar, Index, StorageOrder, UpLo, ConjugateLhs, ConjugateRhs, Version>::run(Index, const Scalar*, Index, const Scalar*, Scalar*, Scalar) [with Scalar = double; Index = long int; int StorageOrder = 0; int UpLo = 1; bool ConjugateLhs = false; bool ConjugateRhs = false; int Version = 0]’ declared here
   41 | void selfadjoint_matrix_vector_product<Scalar,Index,StorageOrder,UpLo,ConjugateLhs,ConjugateRhs,Version>::run(
      |      ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

That looks like it's entirely in Eigen but I haven't looked closely.

Current workaround is to remove the fuse_viz `Werror`

### CODE REVIEW

**Comment by lucasw** [comment]
I'm trying to make this build in Ubuntu 22.10 but getting:

```
/home/lucasw/base_catkin_ws/src/other/fuse/fuse_graphs/include/fuse_graphs/hash_graph.h:426:21: error: ‘ceres::Problem::Options::local_parameterization_ownership’ is deprecated: Local Parameterizations are deprecated. Use Manifold and manifold_ownership instead. [-Werror=deprecated-declarations]
  426 |   archive & options.local_parameterization_ownership;
```

22.10 has ceres 2.1.0

**Comment by svwilliams** [comment]
I swear I've written this before, but I'm not seeing it in this PR history. So either this will be a repeat of a message you have seen before, or I never clicked "send". So apologies either way.

Ceres 2.1 has dramatically changed the implementation of what was previously called LocalParameterization and is now called a Manifold. Making `fuse` support Ceres 2.1 will require a significant time investment. It is something that I intend to support, but likely only in the ROS2 branch. If migrating all of the `fuse` LocalParameterization code into the new Manifold classes is something you want to tackle, we can create a noetic-22.10-devel branch or similar to hold those updates. But it is not something I can implement or maintain at this time.

**Comment by lucasw** [comment]
How about I peel out the commits that don't break ci, get those into another pr- probably just the hpp and maybe ogre.h includes- that'll reduce the diff noise with breaking changes here, make it easier for me to maintain a 22.04+ branch.

**Comment by svwilliams** [comment]
Sounds good. I did push a commit a couple of months ago to get fuse compiling on Ubuntu Jammy. That included some of these changes already.

**Comment by lucasw** [comment]
Right, https://github.com/locusrobotics/fuse/pull/326 has the https://github.com/locusrobotics/fuse/pull/270/commits/d045cc226a391a78bc62ee78065e8fed12c68403 and https://github.com/locusrobotics/fuse/pull/270/commits/98dee7fd6e8d6a2c20d5adf6a7f073a917078426 changes, which only leaves these from https://github.com/locusrobotics/fuse/pull/270/commits/b3da98f0c0146cc3eab5cdd1082bbcb5cd4014de:

```
-#include <OgreVector3.h>
+#include <Ogre.h>
```

File: fuse_viz/src/relative_pose_2d_stamped_constraint_visual.cpp [hunk 1]
```diff
@@ -343,7 +343,13 @@ Ogre::ColourValue RelativePose2DStampedConstraintVisual::computeLossErrorLineCol
   // Get the error line color as HSB:
   Ogre::ColourValue error_line_color(color.r, color.g, color.b);
   Ogre::Real hue, saturation, brightness;
+#if (OGRE_VERSION < ((1 << 16) | (11 << 8) | 0))
```
Comment (svwilliams) [inline fuse_viz/src/relative_pose_2d_stamped_constraint_visual.cpp:347]: Please include the `OgrePrerequisites.h` header to support the `OGRE_VERSION` macro.

**Review by svwilliams — CHANGES_REQUESTED** [review]

File: fuse_viz/src/relative_pose_2d_stamped_constraint_visual.cpp (hunk 1 above)
Comment (lucasw) [reply fuse_viz/src/relative_pose_2d_stamped_constraint_visual.cpp:347]: Done in https://github.com/locusrobotics/fuse/pull/270/commits/5b4dd949514cef2a89dbcd02003094ba186b5262

File: fuse_optimizers/CMakeLists.txt [hunk 2]
```diff
@@ -28,7 +28,7 @@ catkin_package(
 ###########
 ## Build ##
 ###########
-add_compile_options(-Wall -Werror)
+add_compile_options(-Wall)  # -Werror)
```
Comment (lucasw) [inline fuse_optimizers/CMakeLists.txt:31]: I haven't tried restoring Werror here since rebasing these commits on latest, maybe it's not needed now?
