### PR TITLE
Explicitly call boost::range::join

### PR DESCRIPTION
**Pull request by efernandez**
Otherwise we could get a compilation error due to an ambiguous
overloaded `join` function if some `boost/algorithm` headers are
included and somehow leak into `sensor_proc.h`.

The compilation error we'd get is like this:

```bash
In file included from /home/efernandez/dev/ws/cpr_ws/src/fuse/fuse_models/src/odometry_2d_publisher.cpp:36:0:
/home/efernandez/dev/ws/cpr_ws/src/fuse/fuse_models/include/fuse_models/common/sensor_proc.h: In function ‘std::vector<long unsigned int> fuse_models::common::mergeIndices(const std::vector<long unsigned int>&, const std::vector<long unsigned int>&, size_t)’:
/home/efernandez/dev/ws/cpr_ws/src/fuse/fuse_models/include/fuse_models/common/sensor_proc.h:148:154: error: call of overloaded ‘join(const std::vector<long unsigned int>&, const std::vector<long unsigned int>&)’ is ambiguous
   auto merged_indices = boost::copy_range<std::vector<size_t>>(boost::join<const std::vector<size_t>, const std::vector<size_t>>(lhs_indices, rhs_indices));
                                                                                                                                                          ^
In file included from /usr/include/boost/algorithm/string.hpp:24:0,
                 from /home/efernandez/dev/ws/cpr_ws/src/pluginlib/include/pluginlib/./class_loader.hpp:37,
                 from /home/efernandez/dev/ws/cpr_ws/src/pluginlib/include/pluginlib/class_loader.h:35,
                 from /home/efernandez/dev/ws/cpr_ws/src/fuse/fuse_core/include/fuse_core/loss_loader.h:38,
                 from /home/efernandez/dev/ws/cpr_ws/src/fuse/fuse_models/include/fuse_models/parameters/parameter_base.h:37,
                 from /home/efernandez/dev/ws/cpr_ws/src/fuse/fuse_models/include/fuse_models/parameters/odometry_2d_publisher_params.h:37,
                 from /home/efernandez/dev/ws/cpr_ws/src/fuse/fuse_models/include/fuse_models/odometry_2d_publisher.h:37,
                 from /home/efernandez/dev/ws/cpr_ws/src/fuse/fuse_models/src/odometry_2d_publisher.cpp:34:
/usr/include/boost/algorithm/string/join.hpp:46:9: note: candidate: typename boost::range_value<T>::type boost::algorithm::join(const SequenceSequenceT&, const Range1T&) [with SequenceSequenceT = const std::vector<long unsigned int>; Range1T = const std::vector<long unsigned int>; typename boost::range_value<T>::type = long unsigned int]
         join(
         ^
In file included from /home/efernandez/dev/ws/cpr_ws/src/fuse/fuse_models/include/fuse_models/common/sensor_proc.h:65:0,
                 from /home/efernandez/dev/ws/cpr_ws/src/fuse/fuse_models/src/odometry_2d_publisher.cpp:36:
/usr/include/boost/range/join.hpp:76:1: note: candidate: boost::range::joined_range<SinglePassRange1, SinglePassRange2> boost::range::join(SinglePassRange1&, SinglePassRange2&) [with SinglePassRange1 = const std::vector<long unsigned int>; SinglePassRange2 = const std::vector<long unsigned int>]
 join(SinglePassRange1& r1, SinglePassRange2& r2)
 ^
In file included from /home/efernandez/dev/ws/cpr_ws/src/fuse/fuse_models/include/fuse_models/common/sensor_proc.h:65:0,
                 from /home/efernandez/dev/ws/cpr_ws/src/fuse/fuse_models/src/odometry_2d_publisher.cpp:36:
/usr/include/boost/range/join.hpp:66:1: note: candidate: boost::range::joined_range<const SinglePassRange1, const SinglePassRange2> boost::range::join(const SinglePassRange1&, const SinglePassRange2&) [with SinglePassRange1 = const std::vector<long unsigned int>; SinglePassRange2 = const std::vector<long unsigned int>]
 join(const SinglePassRange1& r1, const SinglePassRange2& r2)
 ^
 ```

### CODE REVIEW

**Comment by efernandez** [comment]
@svwilliams You can see from compilation error that `boost/algorithm/string.hpp` leaks from `pluginlib/class_loader.h`, that it's transitively loaded from some `fuse` headers. This has been likely introduced after merging https://github.com/locusrobotics/fuse/pull/118, although the checks didn't failed to compiled :thinking: 

This just failed locally for me after rebasing a local PR on top of the latest `devel` upstream.

**Review by svwilliams — APPROVED** [review]

**Review by ayrton04 — APPROVED** [review]
